server:
  port: 80

#服务别名--注册到consul到注册中心名称
spring:
  application:
    name: cloud-consumer-order
  cloud:
    consul:
      host: 192.168.1.104
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        instance-id: consumer80
        prefer-ip-address: true
        ip-address: 192.168.1.103
