server:
  port: 8006

#服务别名--注册到consul到注册中心名称
spring:
  application:
    name: cloud-provider-payment
  cloud:
    consul:
      host: 192.168.1.104
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        instance-id: payment8001
        prefer-ip-address: true
        ip-address: 192.168.1.103
