#80表示注册到zookeeper服务器的支付服务提供端口号
server:
  port: 9527

#服务别名--注册到eureka到注册中心名称
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # 开启从注册中心动态创建路由的功能，利用微服务名进行路由
      #路由的两种配置方法 1 在配置文件中配置，配置如下，2 在类中的配置，在GateWayConfig
      routes:
        - id: payment-routh #paymentroute #路由的ID 没有固定的规则但要求唯一，建议配合服务名
          #uri: http://localhost:8001  #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service #匹配后提供服务的路由地址 lb负载均衡
          predicates:
            - Path=/payment/get/** # 断言，路径相匹配的进行路由

        - id: payment-routh2 #paymentroute #路由的ID 没有固定的规则但要求唯一，建议配合服务名
          #uri: http://localhost:8001  #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/lb/** # 断言，路径相匹配的进行路由
#            - After=2020-04-26T11:34:32.752+08:00[GMT+08:00] #这个时间点之后再可以使用
#            - Cookie=username,biypm #cookie中需要有username这个值

eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka7001.com:7001/eureka
